//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.27428.2043
// 
namespace WaterQuery.MyWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebService.MyWaterServiceSoap")]
    public interface MyWaterServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProperty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WaterQuery.MyWebService.WaterPropertys> GetPropertyAsync(double P, double T, string Token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WaterPropertys : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double pField;
        
        private double tField;
        
        private double tlField;
        
        private double densityField;
        
        private double hField;
        
        private double hlField;
        
        private double hgField;
        
        private double sField;
        
        private double slField;
        
        private double sgField;
        
        private double vField;
        
        private double cpField;
        
        private double cvField;
        
        private double eField;
        
        private double sSPField;
        
        private double ksField;
        
        private double etaField;
        
        private double uField;
        
        private double rAMDField;
        
        private double pRNField;
        
        private double ePSField;
        
        private double nField;
        
        private double xeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("P");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
                this.RaisePropertyChanged("T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double TL {
            get {
                return this.tlField;
            }
            set {
                this.tlField = value;
                this.RaisePropertyChanged("TL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Density {
            get {
                return this.densityField;
            }
            set {
                this.densityField = value;
                this.RaisePropertyChanged("Density");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double H {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
                this.RaisePropertyChanged("H");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double HL {
            get {
                return this.hlField;
            }
            set {
                this.hlField = value;
                this.RaisePropertyChanged("HL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double HG {
            get {
                return this.hgField;
            }
            set {
                this.hgField = value;
                this.RaisePropertyChanged("HG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
                this.RaisePropertyChanged("S");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
                this.RaisePropertyChanged("SL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double SG {
            get {
                return this.sgField;
            }
            set {
                this.sgField = value;
                this.RaisePropertyChanged("SG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double V {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
                this.RaisePropertyChanged("V");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double Cp {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
                this.RaisePropertyChanged("Cp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double Cv {
            get {
                return this.cvField;
            }
            set {
                this.cvField = value;
                this.RaisePropertyChanged("Cv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
                this.RaisePropertyChanged("E");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double SSP {
            get {
                return this.sSPField;
            }
            set {
                this.sSPField = value;
                this.RaisePropertyChanged("SSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double KS {
            get {
                return this.ksField;
            }
            set {
                this.ksField = value;
                this.RaisePropertyChanged("KS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double Eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
                this.RaisePropertyChanged("Eta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
                this.RaisePropertyChanged("U");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double RAMD {
            get {
                return this.rAMDField;
            }
            set {
                this.rAMDField = value;
                this.RaisePropertyChanged("RAMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double PRN {
            get {
                return this.pRNField;
            }
            set {
                this.pRNField = value;
                this.RaisePropertyChanged("PRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public double EPS {
            get {
                return this.ePSField;
            }
            set {
                this.ePSField = value;
                this.RaisePropertyChanged("EPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public double N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
                this.RaisePropertyChanged("N");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double Xe {
            get {
                return this.xeField;
            }
            set {
                this.xeField = value;
                this.RaisePropertyChanged("Xe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWaterServiceSoapChannel : WaterQuery.MyWebService.MyWaterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWaterServiceSoapClient : System.ServiceModel.ClientBase<WaterQuery.MyWebService.MyWaterServiceSoap>, WaterQuery.MyWebService.MyWaterServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyWaterServiceSoapClient() : 
                base(MyWaterServiceSoapClient.GetDefaultBinding(), MyWaterServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.MyWaterServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyWaterServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MyWaterServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), MyWaterServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyWaterServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyWaterServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyWaterServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyWaterServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyWaterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<WaterQuery.MyWebService.WaterPropertys> GetPropertyAsync(double P, double T, string Token) {
            return base.Channel.GetPropertyAsync(P, T, Token);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.MyWaterServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.MyWaterServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("https://www.songshizhao.com/apps/Water/mywaterservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return MyWaterServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.MyWaterServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return MyWaterServiceSoapClient.GetEndpointAddress(EndpointConfiguration.MyWaterServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            MyWaterServiceSoap,
        }
    }
}
